# -*- coding: utf-8 -*-
"""VIOS1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGexK9encovIZsLBd_7BpoMjUvO3DusK
"""

import pandas as pd
from sklearn import model_selection
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.tree  import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
dataset = pd.read_csv('Iris.csv')
print(dataset)
array = dataset.values
X = array[:,1:5]
Y = array[:, 5]
seed =10
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=seed)
dt = DecisionTreeClassifier()
dt.fit(X_train, Y_train)
predictions = dt.predict(X_test)
Accuracy = accuracy_score(Y_test, predictions)
print("\nAcuuracy\n", Accuracy)
Classification_Report = classification_report(Y_test, predictions)
Confusion_Matrix = confusion_matrix(Y_test, predictions)
print("\nConfusion Matrix\n", Confusion_Matrix)
print("\nClassification Report\n", Classification_Report)

import seaborn as sns
import matplotlib.pyplot as plt
sns.heatmap(Confusion_Matrix,annot=True)
plt.show()

import pandas as pd
df=pd.read_csv("Salary.csv")
print(df)
x=df.drop('Salary',axis=1).values
y=df['Salary'].values
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)
print("slope:",model.coef_)
print("y intercept",model.intercept_)
print(model.predict([[6.5]]))