# -*- coding: utf-8 -*-
"""VOIS4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_mWpHS637BKo-C5fRU4lfLmUau5h50O9
"""

import tensorflow as tf

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

import numpy as np
np.unique(y_train)

label = ['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']

len(label)

import matplotlib.pyplot as plt
i = np.random.randint(1,50000)
op = label[y_train[i][0]]
plt.imshow(x_train[i])
plt.title(f'Image is {op}')
plt.show()

x_train =x_train/255
x_test = x_test/255

ann = tf.keras.Sequential()
ann.add(tf.keras.layers.Flatten(input_shape=(32,32,3)))
ann.add(tf.keras.layers.Dense(2048,activation='relu'))
ann.add(tf.keras.layers.Dense(1024,activation='relu'))
ann.add(tf.keras.layers.Dense(10,activation='softmax'))

ann.summary()

ann.compile(optimizer='adam',loss=tf.keras.losses.SparseCategoricalCrossentropy(),metrics=['accuracy'])

ann.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test))