# -*- coding: utf-8 -*-
"""VOIS 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1brCjBCR12MyLQhshm3ozkK_X3FdCJL5S
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

db1=pd.read_csv('temperatures.csv')
db1.shape

db1.head()

db1.tail()

db1.dtypes

db1.describe()

db1.isnull()

db1["JAN"].mean(axis=0)

from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(var, test_size = 0.25, random_state = 42)
X_train.shape, X_test.shape



tp=80
fp=20
fn=31
tn=70
acc=(tp+tn)/(tp+fp+fn+tn)
pre=tp/(tp+fp)
rec=tp/(tp+fn)
print("Accuracy is : {}".format(acc))
print("Precision is : {}".format(pre))
print("Recall is : {}".format(rec))
print("F1-Score is : {}".format((2*pre*rec)/(pre+rec)))

plt.figure(figsize=(10,10))
sns.heatmap(db1.corr(), annot=True)
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as seabornInstance
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

import pandas as pd
import io
df = pd.read_csv("temperatures.csv")

print(df)

df.plot(x='YEAR', y='JAN', style='o')
plt.title('MinTemp vs MaxTemp')
plt.xlabel('MinTemp')
plt.ylabel('MaxTemp')
plt.show()

X = df['JAN'].values.reshape(-1,1)
y = df['FEB'].values.reshape(-1,1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

regressor = LinearRegression()
regressor.fit(X_train, y_train)

print(regressor.intercept_)
print(regressor.coef_)

y_pred = regressor.predict(X_test)

df = pd.DataFrame({'Actual': y_test.flatten(), 'Predicted': y_pred.flatten()})
df

df1 = df.head(25)
df1.plot(kind='bar',figsize=(16,10))
plt.grid(which='major', linestyle='-', linewidth='0.5', color='green')
plt.grid(which='minor', linestyle=':', linewidth='0.5', color='black')
plt.show()

plt.scatter(X_test, y_test,  color='gray')
plt.plot(X_test, y_pred, color='red', linewidth=2)
plt.show()

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))